/**
 * DaggerQuest – Debug Module Encryption Script
 *
 * Reads the plaintext debug source (scripts/debug-source.js), encrypts it
 * with AES-256-GCM using a SHA-256 hash of the supplied passphrase, and
 * writes the result into src/debug.js as a self-decrypting runtime module.
 *
 * Usage:
 *   node scripts/encryptDebug.js
 *
 * A cryptographically random key is generated each run and printed to
 * the console.  Save it somewhere safe — it cannot be recovered.
 *
 * The generated src/debug.js exposes a single global function:
 *   enableDebug(key)   — call from the browser console to activate debug mode.
 */

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

// ── Generate key ────────────────────────────────────────────────────────

const key = crypto.randomBytes(32).toString('base64url');

// ── Read source ─────────────────────────────────────────────────────────

const sourcePath = path.join(__dirname, 'debug-source.js');
if (!fs.existsSync(sourcePath)) {
    console.error(`Source file not found: ${sourcePath}`);
    process.exit(1);
}
const source = fs.readFileSync(sourcePath, 'utf8');

// ── Encrypt ─────────────────────────────────────────────────────────────

// Derive a 256-bit key from the passphrase using SHA-256
const keyHash = crypto.createHash('sha256').update(key).digest();

// 12-byte random IV (standard for AES-GCM)
const iv = crypto.randomBytes(12);

const cipher = crypto.createCipheriv('aes-256-gcm', keyHash, iv);
let encrypted = cipher.update(source, 'utf8');
encrypted = Buffer.concat([encrypted, cipher.final()]);
const authTag = cipher.getAuthTag(); // 16 bytes

// Web Crypto's AES-GCM decrypt expects the auth tag appended to the
// ciphertext, so we concatenate:  IV (12) + ciphertext + authTag (16)
const payload = Buffer.concat([iv, encrypted, authTag]);
const base64Payload = payload.toString('base64');

// ── Generate src/debug.js ───────────────────────────────────────────────

const output = `/**
 * DaggerQuest – Debug Runtime
 *
 * This file contains an encrypted developer debug module.
 * To activate, open the browser console and call:
 *
 *   enableDebug('your-secret-key')
 *
 * Generated by scripts/encryptDebug.js — do not edit by hand.
 */
(function () {
    var P = '${base64Payload}';

    async function enableDebug(key) {
        try {
            var enc = new TextEncoder();
            var keyData = await crypto.subtle.digest('SHA-256', enc.encode(key));
            var cryptoKey = await crypto.subtle.importKey(
                'raw', keyData, { name: 'AES-GCM' }, false, ['decrypt']
            );
            var raw = Uint8Array.from(atob(P), function (c) { return c.charCodeAt(0); });
            var iv = raw.slice(0, 12);
            var ct = raw.slice(12);
            var decrypted = await crypto.subtle.decrypt(
                { name: 'AES-GCM', iv: iv }, cryptoKey, ct
            );
            var code = new TextDecoder().decode(decrypted);
            new Function(code)();
        } catch (_) {
            console.log('Invalid key.');
        }
    }

    window.enableDebug = enableDebug;
})();
`;

const outputPath = path.join(__dirname, '..', 'src', 'debug.js');
fs.writeFileSync(outputPath, output, 'utf8');

console.log(`Encrypted debug module written to src/debug.js`);
console.log(`Source size : ${source.length} bytes`);
console.log(`Payload size: ${base64Payload.length} chars (base64)`);
console.log(`\nYour debug key:\n\n  ${key}\n`);
console.log(`Activate in browser console with: enableDebug("${key}")`);
